# Generated by Django 4.2.5 on 2023-09-09 12:14

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_telegramuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuserstate',
            name='logs',
            field=models.JSONField(default=users.models.dict_state),
        ),
    ]
