# Generated by Django 4.2.5 on 2023-09-09 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professions', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_resume', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('salary_from', models.BigIntegerField(null=True)),
                ('salary_to', models.BigIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ManyToManyField(related_name='application', through='vacancies.Application', to='resumes.resume')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancy_owner', to=settings.AUTH_USER_MODEL)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancy_profession', to='professions.profession')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancys',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_vacancy', to='vacancies.vacancy'),
        ),
    ]
