# Generated by Django 4.2.5 on 2023-09-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Profession Area',
                'verbose_name_plural': 'Profession Areas',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('profession_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profession_area', to='professions.professionarea')),
            ],
            options={
                'verbose_name': 'Profession Area',
                'verbose_name_plural': 'Profession Areas',
            },
        ),
    ]
